import { useEffect, useMemo, useState } from 'react'
import type { ActiveSession, AnswerKey, BankIndex, Question, QuestionProgress, QuestionnaireMeta, StudySessionRecord, StudySource } from './types'
import { addSession, clearAllData, clearLocalCache, exportDatabase, getAllProgress, getRecentSessions, importProgress, pushLocalSnapshotToCloud, putProgress, synchronizeAccount } from './db'
import { cloudConfigured, getSession, signIn, signOut, supabase } from './supabase'
import type { Session } from '@supabase/supabase-js'
import { loadAllQuestions, loadBankIndex, loadQuestionnaire, resolveQuestions } from './data'
import { chooseSmartQuestions, getStatus, needsReview, percent, shuffle } from './utils'

const ACTIVE='cap-test-active-v1', LAST='cap-test-last-v1', THEME='cap-test-theme'
type Route='home'|'study'|'questionnaires'|'exam'|'quiz'|'results'|'stats'|'settings'
const route=():Route=>{const r=location.hash.replace(/^#\/?/,'').split('?')[0] as Route;return ['home','study','questionnaires','exam','quiz','results','stats','settings'].includes(r)?r:'home'}
const go=(r:Route)=>location.hash='#/'+r
const group=(q:Question)=>q.section+':'+q.questionnaireId
const fresh=(q:Question):QuestionProgress=>({questionId:q.id,questionnaireId:group(q),attempts:0,correct:0,incorrect:0,streak:0,lastAnsweredAt:0,favorite:false})
const keys:AnswerKey[]=['A','B','C','D']

function Bar({v}:{v:number}){return <div className="bar"><i style={{width:Math.max(0,Math.min(100,v))+'%'}}/></div>}
function Btn({children,onClick,kind='primary',disabled=false}:{children:any,onClick?:()=>void,kind?:string,disabled?:boolean}){return <button className={'btn '+kind} onClick={onClick} disabled={disabled}>{children}</button>}
function Loading({text='Cargando…'}:{text?:string}){return <div className="center"><span className="spinner"/><b>{text}</b></div>}

function Login({onSuccess}:{onSuccess:(session:Session)=>Promise<void>}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false)
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setSending(true);try{const session=await signIn(email.trim(),password);if(!session)throw new Error('No se pudo iniciar sesión.');await onSuccess(session)}catch(err:any){console.error(err);setError('Email o contraseña no válidos.')}finally{setSending(false)}}
 return <div className="authshell"><section className="authcard"><div className="authlogo">CT</div><em>CAP TEST 2026</em><h1>Tu progreso, siempre contigo.</h1><p>Inicia sesión para conservar resultados, errores y estadísticas en todos tus dispositivos.</p><form onSubmit={submit}><label>Email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Contraseña<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="autherror">{error}</div>}<button className="btn primary" disabled={sending}>{sending?'Entrando…':'Entrar'}</button></form><small>Acceso privado. No hay registro público desde esta página.</small></section></div>
}

function App(){
 const [session,setSession]=useState<Session|null>(null),[authReady,setAuthReady]=useState(false),[syncing,setSyncing]=useState(false)
 useEffect(()=>{let live=true;if(!cloudConfigured||!supabase){setAuthReady(true);return}getSession().then(async current=>{if(!live)return;if(current){setSyncing(true);try{await synchronizeAccount()}finally{if(live)setSyncing(false)}}if(live)setSession(current)}).catch(console.error).finally(()=>{if(live)setAuthReady(true)});return()=>{live=false}},[])
 async function loginDone(next:Session){setSyncing(true);try{await synchronizeAccount();setSession(next)}finally{setSyncing(false);setAuthReady(true)}}
 async function logout(){try{await signOut()}finally{await clearLocalCache();sessionStorage.removeItem(ACTIVE);sessionStorage.removeItem(LAST);setSession(null)}}
 if(!cloudConfigured)return <div className="authshell"><section className="authcard"><div className="authlogo">CT</div><h1>Sincronización pendiente</h1><p>La aplicación está preparada para acceso privado, pero falta conectar el proyecto de Supabase.</p></section></div>
 if(!authReady||syncing)return <Loading text={syncing?'Sincronizando tu progreso…':'Comprobando sesión…'}/>
 if(!session)return <Login onSuccess={loginDone}/>
 return <CapApp userEmail={session.user.email||'Usuario'} onSignOut={logout}/>
}

function CapApp({userEmail,onSignOut}:{userEmail:string;onSignOut:()=>Promise<void>}){
 const [page,setPage]=useState<Route>(route()),[bank,setBank]=useState<BankIndex|null>(null),[rows,setRows]=useState<QuestionProgress[]>([]),[sessions,setSessions]=useState<StudySessionRecord[]>([]),[busy,setBusy]=useState(true),[load,setLoad]=useState<number|null>(null),[online,setOnline]=useState(navigator.onLine),[theme,setTheme]=useState(localStorage.getItem(THEME)||'light')
 useEffect(()=>{const h=()=>setPage(route()),o=()=>{const isOnline=navigator.onLine;setOnline(isOnline);if(isOnline)pushLocalSnapshotToCloud().catch(console.error)};addEventListener('hashchange',h);addEventListener('online',o);addEventListener('offline',o);if(!location.hash)go('home');return()=>{removeEventListener('hashchange',h);removeEventListener('online',o);removeEventListener('offline',o)}},[])
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem(THEME,theme)},[theme])
 const refresh=async()=>{setRows(await getAllProgress());setSessions(await getRecentSessions(30))}
 useEffect(()=>{Promise.all([loadBankIndex(),refresh()]).then(([b])=>setBank(b)).finally(()=>setBusy(false))},[])
 const pm=useMemo(()=>new Map(rows.map(x=>[x.questionId,x])),[rows])
 const stats=useMemo(()=>{const seen=rows.filter(x=>x.attempts).length,mastered=rows.filter(x=>getStatus(x)==='mastered').length,review=rows.filter(x=>needsReview(x)).length,fav=rows.filter(x=>x.favorite).length,attempts=rows.reduce((a,x)=>a+x.attempts,0),correct=rows.reduce((a,x)=>a+x.correct,0),total=bank?.totalQuestions||0;return{seen,mastered,review,fav,attempts,correct,total,acc:percent(correct,attempts),coverage:percent(seen,total)}},[rows,bank])
 async function start(type:'study'|'exam',source:StudySource,count:number,label:string,meta?:QuestionnaireMeta){
  setLoad(0);let pool=meta?await loadQuestionnaire(meta):await loadAllQuestions((d,t)=>setLoad(percent(d,t)));setLoad(null)
  if(source==='unseen')pool=pool.filter(q=>!pm.get(q.id)?.attempts)
  if(source==='errors')pool=pool.filter(q=>needsReview(pm.get(q.id)))
  if(source==='favorites')pool=pool.filter(q=>pm.get(q.id)?.favorite)
  if(source==='smart')pool=chooseSmartQuestions(pool,pm,Math.min(count,pool.length))
  else if(source==='questionnaire')pool=[...pool].sort((a,b)=>{const score={review:0,unseen:1,learning:2,mastered:3};return score[getStatus(pm.get(a.id))]-score[getStatus(pm.get(b.id))]||Math.random()-.5}).slice(0,count)
  else pool=shuffle(pool).slice(0,count)
  if(!pool.length){alert(source==='errors'?'No tienes errores pendientes.':source==='favorites'?'No tienes favoritas todavía.':'No hay preguntas con ese filtro.');return}
  const s:ActiveSession={type,source,label,questionIds:pool.map(q=>q.id),questionnaireId:meta?.id,currentIndex:0,selectedAnswers:{},checkedIds:[],startedAt:Date.now()};sessionStorage.setItem(ACTIVE,JSON.stringify(s));go('quiz')
 }
 if(busy||!bank)return <Loading text="Preparando CAP Test…"/>
 const props={bank,rows,pm,stats,sessions,start}
 return <div className="app">
  <header><button className="logo" onClick={()=>go('home')}>CT</button><div><b>{page==='home'?'CAP Test 2026':({study:'Modo estudio',questionnaires:'Cuestionarios',exam:'Simulacro',quiz:'Test en curso',results:'Resultado',stats:'Progreso',settings:'Ajustes'} as any)[page]}</b>{!online&&<small>Sin conexión</small>}</div><button className="gear" onClick={()=>go('settings')}>⚙</button></header>
  <main>{load!==null&&<div className="overlay"><Loading text={'Preparando preguntas… '+load+'%'}/></div>}{page==='home'&&<Home {...props}/>} {page==='study'&&<Study {...props}/>} {page==='questionnaires'&&<Questionnaires {...props}/>} {page==='exam'&&<Exam {...props}/>} {page==='quiz'&&<Quiz pm={pm} refresh={refresh}/>} {page==='results'&&<Results/>} {page==='stats'&&<Stats {...props}/>} {page==='settings'&&<Settings theme={theme} setTheme={setTheme} bank={bank} refresh={refresh} userEmail={userEmail} onSignOut={onSignOut}/>}</main>
  {!['quiz','results','settings','questionnaires'].includes(page)&&<nav><button className={page==='home'?'on':''} onClick={()=>go('home')}>⌂<span>Inicio</span></button><button className={page==='study'?'on':''} onClick={()=>go('study')}>▤<span>Estudiar</span></button><button className={page==='exam'?'on':''} onClick={()=>go('exam')}>✓<span>Test</span></button><button className={page==='stats'?'on':''} onClick={()=>go('stats')}>◫<span>Progreso</span></button></nav>}
 </div>
}

type P={bank:BankIndex;rows:QuestionProgress[];pm:Map<string,QuestionProgress>;stats:any;sessions:StudySessionRecord[];start:(t:'study'|'exam',s:StudySource,c:number,l:string,m?:QuestionnaireMeta)=>Promise<void>}

function Home({bank,stats,sessions,start}:P){return <div className="page">
 <section className="hero"><div><em>BANCO CAP 2026</em><h1>Estudia a tu ritmo.<br/>Aprende de cada fallo.</h1><p>{bank.totalQuestions.toLocaleString('es-ES')} preguntas · {bank.totalQuestionnaires} cuestionarios</p></div><strong>{stats.coverage}%<small>visto</small></strong></section>
 <div className="metrics"><article><small>Precisión</small><b>{stats.attempts?stats.acc+'%':'—'}</b><span>{stats.attempts} respuestas</span></article><article><small>Dominadas</small><b>{stats.mastered}</b><span>3 aciertos seguidos</span></article><article><small>Por repasar</small><b>{stats.review}</b><span>errores activos</span></article></div>
 <h2>¿Qué quieres hacer?</h2><div className="cards"><button onClick={()=>start('study','smart',20,'Repaso inteligente')}>✦<span><b>Repaso inteligente</b><small>Prioriza lo que más necesitas</small></span>›</button><button onClick={()=>go('questionnaires')}>▦<span><b>Por cuestionario</b><small>Avanza bloque a bloque</small></span>›</button><button onClick={()=>start('study','errors',20,'Mis errores')}>×<span><b>Mis errores</b><small>{stats.review} pendientes</small></span>›</button><button onClick={()=>go('exam')}>✓<span><b>Simulacro</b><small>Corrección al final</small></span>›</button></div>
 {sessions[0]&&<div className="recent"><div><small>ÚLTIMA SESIÓN</small><b>{sessions[0].label}</b></div><strong>{sessions[0].score}%</strong></div>}<p className="note">Herramienta de estudio basada en el banco proporcionado. No es un servicio oficial de la DGT.</p>
 </div>}

function Study({stats,start}:P){return <div className="page"><em>MODO ESTUDIO</em><h1>Corrección inmediata</h1><p>Marca una respuesta, comprueba al instante y consulta la norma o referencia.</p><div className="list">
 {([['✦','Repaso inteligente','smart',20,'Errores, baja precisión y preguntas olvidadas.'],['○','Preguntas nuevas','unseen',20,'Solo preguntas que aún no has contestado.'],['×','Test de errores','errors',20,stats.review+' pendientes de consolidar.'],['★','Favoritas','favorites',20,stats.fav+' guardadas.'],['⤨','Aleatorio','random',20,'20 preguntas de todo el banco.']] as any[]).map(x=><button key={x[2]} onClick={()=>start('study',x[2],x[3],x[1])}><i>{x[0]}</i><span><b>{x[1]}</b><small>{x[4]}</small></span>›</button>)}
 <button onClick={()=>go('questionnaires')}><i>▦</i><span><b>Elegir cuestionario</b><small>Estudia una sección concreta.</small></span>›</button></div><div className="tip"><b>¿Cuándo sale de errores?</b><p>Con 2 aciertos consecutivos deja de estar pendiente. Con 3 pasa a “Dominada”.</p></div></div>}

function Questionnaires({bank,rows,start}:P){return <div className="page"><button className="back" onClick={()=>history.back()}>‹ Volver</button><h1>Cuestionarios</h1>{[...new Set(bank.questionnaires.map(q=>q.section))].map(sec=><section key={sec}><em>SECCIÓN {sec.replace(';',' / ')}</em><div className="qgrid">{bank.questionnaires.filter(q=>q.section===sec).map(m=>{const k=m.section+':'+m.questionnaireId,r=rows.filter(x=>x.questionnaireId===k),seen=r.filter(x=>x.attempts).length,att=r.reduce((a,x)=>a+x.attempts,0),cor=r.reduce((a,x)=>a+x.correct,0),cov=percent(seen,m.count);return <article key={m.id}><div className="qtop"><span>{m.questionnaireId}</span><b>{cov}%</b></div><h3>{m.title}</h3><small>{m.count} preguntas · {seen?percent(cor,att)+'% acierto':'Sin empezar'}</small><Bar v={cov}/><div className="actions"><Btn onClick={()=>start('study','questionnaire',Math.min(20,m.count),m.title+' · estudio',m)}>Estudiar 20</Btn><Btn kind="light" onClick={()=>start('study','questionnaire',m.count,m.title+' · completo',m)}>Todas</Btn></div></article>})}</div></section>)}</div>}

function Exam({bank,stats,start}:P){const [count,setCount]=useState(30),[source,setSource]=useState<StudySource>('random'),[qid,setQid]=useState(bank.questionnaires[0].id);const meta=bank.questionnaires.find(x=>x.id===qid);return <div className="page"><em>SIMULACRO</em><h1>Como un examen</h1><p>No verás la solución hasta finalizar. Las no contestadas cuentan como fallo.</p><div className="panel"><label>Número de preguntas</label><div className="segments">{[10,20,30,50].map(n=><button className={count===n?'on':''} onClick={()=>setCount(n)} key={n}>{n}</button>)}</div><label>Contenido</label>{([['random','Todo el banco','Mezcla todos los cuestionarios'],['unseen','Solo nuevas',(stats.total-stats.seen)+' sin ver'],['errors','Solo errores',stats.review+' disponibles'],['questionnaire','Un cuestionario','Elige un bloque concreto']] as any[]).map(x=><button className={'radio '+(source===x[0]?'on':'')} onClick={()=>setSource(x[0])} key={x[0]}><i/><span><b>{x[1]}</b><small>{x[2]}</small></span></button>)}{source==='questionnaire'&&<select value={qid} onChange={e=>setQid(e.target.value)}>{bank.questionnaires.map(q=><option key={q.id} value={q.id}>Sección {q.section} · {q.questionnaireId} ({q.count})</option>)}</select>}<Btn onClick={()=>start('exam',source,count,'Simulacro · '+count,source==='questionnaire'?meta:undefined)}>Comenzar simulacro</Btn></div></div>}

function Quiz({pm,refresh}:{pm:Map<string,QuestionProgress>;refresh:()=>Promise<void>}){const [s,setS]=useState<ActiveSession|null>(()=>JSON.parse(sessionStorage.getItem(ACTIVE)||'null')),[qs,setQs]=useState<Question[]>([]),[loading,setLoading]=useState(true),[ref,setRef]=useState(false)
 useEffect(()=>{if(!s){go('study');return}resolveQuestions(s.questionIds).then(x=>{setQs(x);setLoading(false)})},[])
 if(!s||loading||!qs.length)return <Loading text="Cargando test…"/>
 const session=s
 const i=session.currentIndex,q=qs[i],sel=session.selectedAnswers[q.id],checked=session.checkedIds.includes(q.id),correct=sel===q.correctAnswer,fav=pm.get(q.id)?.favorite
 const save=(n:ActiveSession)=>{setS(n);sessionStorage.setItem(ACTIVE,JSON.stringify(n))}
 const select=(k:AnswerKey)=>{if(session.type==='study'&&checked)return;save({...session,selectedAnswers:{...session.selectedAnswers,[q.id]:k}})}
 async function check(){if(!sel||checked)return;const b=pm.get(q.id)||fresh(q),ok=sel===q.correctAnswer;await putProgress({...b,attempts:b.attempts+1,correct:b.correct+(ok?1:0),incorrect:b.incorrect+(ok?0:1),streak:ok?b.streak+1:0,lastAnsweredAt:Date.now(),lastAnswer:sel,lastCorrect:ok});save({...session,checkedIds:[...session.checkedIds,q.id]});await refresh()}
 async function favorite(){const b=pm.get(q.id)||fresh(q);await putProgress({...b,favorite:!b.favorite});await refresh()}
 async function finish(){if(session.type==='exam')for(const x of qs){const a=session.selectedAnswers[x.id],b=pm.get(x.id)||fresh(x),ok=a===x.correctAnswer;await putProgress({...b,attempts:b.attempts+1,correct:b.correct+(ok?1:0),incorrect:b.incorrect+(ok?0:1),streak:ok?b.streak+1:0,lastAnsweredAt:Date.now(),lastAnswer:a,lastCorrect:ok})}const answers=qs.map(x=>({questionId:x.id,questionnaireId:group(x),selected:session.selectedAnswers[x.id],correctAnswer:x.correctAnswer,correct:session.selectedAnswers[x.id]===x.correctAnswer})),cor=answers.filter(x=>x.correct).length,ans=answers.filter(x=>x.selected).length,r:StudySessionRecord={type:session.type,label:session.label,startedAt:session.startedAt,completedAt:Date.now(),total:qs.length,answered:ans,correct:cor,incorrect:qs.length-cor,score:percent(cor,qs.length),answers};await addSession(r);sessionStorage.setItem(LAST,JSON.stringify({record:r,questionIds:session.questionIds}));sessionStorage.removeItem(ACTIVE);await refresh();go('results')}
 return <div className="quiz"><div className="quizhead"><button onClick={()=>history.back()}>×</button><div><b>{session.label}</b><small>{i+1} de {qs.length}</small><Bar v={percent(i+1,qs.length)}/></div><button className={fav?'fav':''} onClick={favorite}>★</button></div><article><small>Pregunta {i+1} · COD {q.code}</small><h2>{q.question}</h2><div className="answers">{keys.map(k=>{let c=sel===k?'selected':'';if(session.type==='study'&&checked)c=k===q.correctAnswer?'correct':sel===k?'wrong':'';return <button className={c} onClick={()=>select(k)} key={k}><i>{k}</i><span>{q.options[k]}</span></button>})}</div>{session.type==='study'&&!checked&&<Btn disabled={!sel} onClick={check}>Comprobar respuesta</Btn>}{session.type==='study'&&checked&&<div className={'feedback '+(correct?'ok':'bad')}><b>{correct?'✓ ¡Correcto!':'× Incorrecto · correcta '+q.correctAnswer}</b><button onClick={()=>setRef(!ref)}>{ref?'Ocultar':'Ver fundamento'}</button>{ref&&<div><p><b>Norma:</b> {q.norm}</p><p><b>Referencia:</b> {q.reference}</p></div>}</div>}</article><footer><Btn kind="light" disabled={i===0} onClick={()=>save({...session,currentIndex:i-1})}>Anterior</Btn>{i<qs.length-1?<Btn disabled={session.type==='study'&&!checked} onClick={()=>{setRef(false);save({...session,currentIndex:i+1})}}>Siguiente</Btn>:<Btn disabled={session.type==='study'&&!checked} onClick={finish}>Finalizar</Btn>}</footer></div>}

function Results(){const data=JSON.parse(sessionStorage.getItem(LAST)||'null') as {record:StudySessionRecord;questionIds:string[]}|null,[qs,setQs]=useState<Question[]>([]);useEffect(()=>{if(data)resolveQuestions(data.questionIds).then(setQs)},[]);if(!data)return <Loading/>;const r=data.record,map=new Map(qs.map(q=>[q.id,q])),fails=r.answers.filter(a=>!a.correct);async function review(){const a:ActiveSession={type:'study',source:'errors',label:'Repaso del último test',questionIds:fails.map(x=>x.questionId),currentIndex:0,selectedAnswers:{},checkedIds:[],startedAt:Date.now()};sessionStorage.setItem(ACTIVE,JSON.stringify(a));go('quiz')}return <div className="page"><button className="back" onClick={()=>go('home')}>‹ Inicio</button><section className={'result '+(r.score>=80?'good':r.score>=60?'mid':'bad')}><em>RESULTADO</em><strong>{r.score}%</strong><h1>{r.score>=80?'Muy buen resultado':r.score>=60?'Buen intento':'Toca reforzar'}</h1><p>{r.label}</p></section><div className="metrics"><article><b>{r.correct}</b><span>Correctas</span></article><article><b>{r.incorrect}</b><span>Fallos</span></article><article><b>{r.total-r.answered}</b><span>Sin responder</span></article></div>{fails.length>0&&<Btn onClick={review}>Repasar {fails.length} fallos</Btn>}<h2>Respuestas a revisar</h2><div className="review">{fails.map(a=>{const q=map.get(a.questionId);return q?<article key={q.id}><b>{q.question}</b><p>Tu respuesta: {a.selected||'Sin responder'}</p><p className="green">Correcta: {q.correctAnswer} · {q.options[q.correctAnswer]}</p></article>:null})}</div></div>}

function Stats({bank,rows,stats,sessions}:P){return <div className="page"><em>TU PREPARACIÓN</em><h1>{stats.attempts?stats.acc+'%':'Empieza hoy'}</h1><p>{stats.attempts?'de precisión global':'Tus estadísticas aparecerán aquí.'}</p><div className="statsgrid"><article><small>Vistas</small><b>{stats.seen}</b><span>de {stats.total}</span></article><article><small>Dominadas</small><b>{stats.mastered}</b></article><article><small>Por repasar</small><b>{stats.review}</b></article><article><small>Favoritas</small><b>{stats.fav}</b></article></div><h2>Progreso por cuestionario</h2><div className="progresslist">{bank.questionnaires.map(m=>{const rr=rows.filter(x=>x.questionnaireId===m.section+':'+m.questionnaireId),seen=rr.filter(x=>x.attempts).length;if(!seen)return null;const att=rr.reduce((a,x)=>a+x.attempts,0),cor=rr.reduce((a,x)=>a+x.correct,0);return <div key={m.id}><span><b>{m.questionnaireId}</b> · Sección {m.section}</span><small>{seen}/{m.count} · {percent(cor,att)}%</small><Bar v={percent(seen,m.count)}/></div>})}</div><h2>Últimas sesiones</h2><div className="history">{sessions.slice(0,10).map((s,i)=><div key={i}><span><b>{s.label}</b><small>{s.total} preguntas</small></span><strong>{s.score}%</strong></div>)}</div></div>}

function Settings({theme,setTheme,bank,refresh,userEmail,onSignOut}:{theme:string;setTheme:(s:string)=>void;bank:BankIndex;refresh:()=>Promise<void>;userEmail:string;onSignOut:()=>Promise<void>}){async function backup(){const d=await exportDatabase(),b=new Blob([JSON.stringify(d,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='cap-test-backup.json';a.click();URL.revokeObjectURL(u)}async function restore(e:any){const f=e.target.files?.[0];if(!f)return;const d=JSON.parse(await f.text());if(!Array.isArray(d.progress))return alert('Copia no válida');await importProgress(d.progress);await refresh();alert('Progreso importado')}async function reset(){if(confirm('¿Borrar todo el progreso de tu cuenta? Esta acción afectará a todos tus dispositivos.')){await clearAllData();await refresh()}}return <div className="page"><button className="back" onClick={()=>history.back()}>‹ Volver</button><h1>Ajustes</h1><div className="panel account"><small>CUENTA</small><h2>{userEmail}</h2><p>Tu progreso está sincronizado con tu cuenta y disponible en cualquier dispositivo donde inicies sesión.</p><Btn kind="light" onClick={()=>void onSignOut()}>Cerrar sesión</Btn></div><div className="panel"><label>Tema</label><div className="segments"><button className={theme==='light'?'on':''} onClick={()=>setTheme('light')}>☀ Claro</button><button className={theme==='dark'?'on':''} onClick={()=>setTheme('dark')}>◐ Oscuro</button></div></div><div className="panel"><h2>Copia de seguridad</h2><p>Tu progreso se guarda en tu cuenta. Esta copia sirve como respaldo manual.</p><div className="actions"><Btn kind="light" onClick={backup}>↓ Exportar</Btn><label className="btn light">↑ Importar<input type="file" accept=".json" hidden onChange={restore}/></label></div></div><div className="panel"><h2>Banco CAP 2026</h2><p>{bank.totalQuestions.toLocaleString('es-ES')} preguntas · {bank.totalQuestionnaires} cuestionarios · {bank.version}</p></div><div className="panel danger"><h2>Empezar de cero</h2><Btn kind="danger" onClick={reset}>Borrar todo mi progreso</Btn></div></div>}

export default App
